//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DongTaoShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public decimal Id { get; set; }
        public int IdTaiKhoan { get; set; }
        public int IdSanPham { get; set; }
        public int DanhGia { get; set; }
        public string BinhLuan1 { get; set; }
        public bool DaTraLoi { get; set; }
        public string NoiDungTraLoi { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
