//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DongTaoShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public long Id { get; set; }
        public Nullable<int> IdSanPham { get; set; }
        public Nullable<int> IdNguoiMua { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> MuaLanDau { get; set; }
        public Nullable<bool> MuaNhieu { get; set; }
        public Nullable<bool> ThanhVien { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> TongCong { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
